import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useTranslation, Trans } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import dataJson from '../json/data.json'
import { KVTyper } from '../components/kv-typer'

import { useRouter } from 'next/router'

const Home: NextPage = (props) => {
  const { data } = props
  console.log(useRouter())
  console.log(props)

  const router = useRouter()
  const { t } = useTranslation(['common', 'typer'])

  console.log('useTranslation')
  console.log(useTranslation())
  console.log(data)

  return (
    <div>
      <Head>
        <title>Shueny Wang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <KVTyper data={data['typer']} />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

// const getStaticProps = makeStaticProps(['common'])
const getStaticProps = async ({ locale }: any) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'about', 'typer'])),
    data: dataJson,
    fallback: false,
  },
})

export { getStaticProps }
