name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ... other steps
      - name: Install dependencies
        run: pnpm install
      
      - name: Build project
        run: pnpm build
        env:
          ASTRO_ADAPTER_MODE: serverless # Set the adapter mode explicitly